services:
  app:
    image: 'my-tasklist:latest'
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - P_URL=${DB_URL}
      - P_USERNAME=${DB_USER}
      - P_PASSWORD=${DB_PASSWORD}
      - SECRET=${SECRET}
      - REDIS_HOST=redis_db
    depends_on:
      - postgres_db
      - redis_db
    networks:
      - my_network

  postgres_db:
    image: 'postgres:15'
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  redis_db:
    image: 'redis:7'
    container_name: redis_db
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
